[SISCAP-92] Garantia de fluxo de navegação de usuário
sep-es-br/siscap-web pull request #21
Opened 2024-03-27 15:58 UTC by AUFaria

2024-03-27 17:00 UTC, wbcrux commented on src/main.ts
Remover comentário

2024-03-27 17:02 UTC, wbcrux commented on src/app/shared/services/toast-notifier/toast-notifier.service.ts
Não havendo diferenças, por que criar uma função pra cada tipo de emissão sendo que o tipo já é fornecido?

2024-03-27 17:34 UTC, AUFaria commented on src/main.ts
O código não é um comentário.

[Angular - Add the localize package](https://angular.io/guide/i18n-common-add-package)

2024-03-27 17:36 UTC, AUFaria commented on src/app/shared/utils/toast-info-map.ts
Ajustado em https://github.com/sep-es-br/siscap-web/pull/21/commits/695ecef8e60a361f67f8eef7245dd5542f259084.

2024-03-27 19:08 UTC, AUFaria commented on src/app/shared/services/toast-notifier/toast-notifier.service.ts
Ajustado em https://github.com/sep-es-br/siscap-web/pull/21/commits/487a5aa07124dfe47b007687bd9e0e2e5b5535d6 e https://github.com/sep-es-br/siscap-web/pull/21/commits/9ada3da06324e04a149e3cb4f806ee85aca3baa0

2024-03-27 19:14 UTC, AUFaria commented on src/app/components/toast/toast.component.html
Ajustado em https://github.com/sep-es-br/siscap-web/pull/21/commits/1f561c896eb98e026500fd5dcb5efa61d26df53a, https://github.com/sep-es-br/siscap-web/pull/21/commits/e1d3071142ee4ff0990b3568e41ae94b24f6bf2f e https://github.com/sep-es-br/siscap-web/pull/21/commits/229d8a3aabf8c7dbe5df5efa055dd186489ba053

2024-03-27 19:24 UTC, AUFaria commented on src/app/components/toast/toast.component.ts
Ajustado em https://github.com/sep-es-br/siscap-web/pull/21/commits/97cc629a809d19ba9dadf67222ed8b140aaaf81d e https://github.com/sep-es-br/siscap-web/pull/21/commits/8c1ebdfcc8eaa350b89e5afbf416e40b35b0d9b9

2024-03-28 11:30 UTC, wbcrux requested changes

2024-03-28 11:30 UTC, wbcrux commented on src/app/components/toast/toast.component.html
Defina as classes (bg-danger-subtle, bg-success-subtle, bg-warning-subtle) condicionais de acordo com o tipo da mensagem.
Um único ng-container genérico para a exibição do toast com as classes acima definidas de acordo com o respectivo tipo.

2024-03-28 11:30 UTC, wbcrux commented on src/app/components/toast/toast.component.ts
O defasult não foi definido

2024-03-28 19:16 UTC, AUFaria commented on src/app/components/toast/toast.component.html
Ajustado em https://github.com/sep-es-br/siscap-web/pull/21/commits/2a7f00e22df8f2c78f9242631dfe0a81cc131f83

2024-03-28 19:17 UTC, AUFaria commented on src/app/components/toast/toast.component.ts
Ajustado em https://github.com/sep-es-br/siscap-web/pull/21/commits/2a7f00e22df8f2c78f9242631dfe0a81cc131f83

2024-03-28 19:42 UTC, wbcrux requested changes

2024-03-28 19:42 UTC, wbcrux commented on src/app/shared/utils/toast-info-map.ts
As mensagens de erro recebidas do backend devem ser exibidas.

2024-04-01 13:26 UTC, AUFaria commented on src/app/shared/utils/toast-info-map.ts
Ajustado em https://github.com/sep-es-br/siscap-web/pull/21/commits/1f0c90661701f1a7751e6eb743747e7cac5915e8 e https://github.com/sep-es-br/siscap-web/pull/21/commits/70ad2f9bdecb7eeb55e5d40116b0c7794005f54e

2024-04-01 16:03 UTC, wbcrux approved these changes

2024-04-01 16:03 UTC, merged